name: Waka Readme

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Update WakaTime Readme
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # content
          SECTION_NAME: waka
          PULL_BRANCH_NAME: true
          PUSH_BRANCH_NAME: true
          SHOW_OS: true
          SHOW_PROJECTS: true
          SHOW_EDITORS: true
          SHOW_TIMEZONE: true
          SHOW_COMMIT: true
          SHOW_LANGUAGE: true
          SHOW_LANGUAGE_PER_REPO: true
          SHOW_LOC_CHART: true
          SHOW_DAYS_OF_WEEK: true
          SHOW_PROFILE_VIEWS: true
          SHOW_SHORT_INFO: true
          SHOW_UPDATED_DATE: true
          SHOW_TOTAL_CODE_TIME: true
          # commit
          COMMIT_MESSAGE: Updated waka-readme graph with new metrics
